portfolio:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: portfolio
      schema: main
      schemas_and_paths:
        main: ../data/db.sqlite
      schema_directory: ../data
